### ISSUE TITLE
generateChangeLog feature not working

### ISSUE THREAD

**Issue by alexandru-slobodcicov** [liquibase/liquibase-mongodb#119]
Yeah thank you for the support and I've actually established the connection as per the below given logs but still having issue with the successful execution onwards as I am integrating liquibase for the first time that too with mongo so facing a bit issues regarding configurations.

Pls have  a look on the following code snippet and guide further how can I proceed with this.

`

```
[2021-04-01 19:59:56] FINE [liquibase.database] Properties:
[2021-04-01 19:59:57] FINE [liquibase.database] Key:'password' Value:'**********'
[2021-04-01 19:59:57] FINE [liquibase.database] Key:'user' Value:''
[2021-04-01 19:59:57] FINE [liquibase.database] Connecting to the URL:'mongodb://localhost:27017/test' using driver:'liquibase.ext.mongodb.database.MongoClientDriver'
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.database.DatabaseConnection instance liquibase.database.jvm.JdbcConnection
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.database.DatabaseConnection instance com.datical.liquibase.ext.database.jvm.ProJdbcConnection
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.database.DatabaseConnection instance liquibase.ext.mongodb.database.MongoConnection
[2021-04-01 19:59:57] WARNING [com.mongodb.diagnostics.logging.Loggers shouldUseSLF4J] SLF4J not found on the classpath.  Logging is disabled for the 'org.mongodb.driver' component
[2021-04-01 19:59:57] FINE [liquibase.database] Connection has been created
[2021-04-01 19:59:57] FINE [liquibase.ext] Connected to @localhost:27017
[2021-04-01 19:59:57] FINE [liquibase.ext] Not adjusting the auto commit mode; it is already false
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.Catalog
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.Column
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.Data
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.ForeignKey
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.Index
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.PrimaryKey
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.Schema
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.Sequence
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.StoredProcedure
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.Table
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.UniqueConstraint
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.View
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance com.datical.liquibase.ext.appdba.synonym.Synonym
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance com.datical.liquibase.ext.storedlogic.checkconstraint.CheckConstraint
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance com.datical.liquibase.ext.storedlogic.databasepackage.DatabasePackage
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance com.datical.liquibase.ext.storedlogic.databasepackage.DatabasePackageBody
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance com.datical.liquibase.ext.storedlogic.function.Function
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance com.datical.liquibase.ext.storedlogic.trigger.Trigger
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance liquibase.command.core.DeactivateChangeLogCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance liquibase.command.core.DiffCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance liquibase.command.core.DiffToChangeLogCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance liquibase.command.core.DropAllCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance liquibase.command.core.ExecuteSqlCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance liquibase.command.core.GenerateChangeLogCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance liquibase.command.core.HistoryCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance liquibase.command.core.RegisterChangeLogCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance liquibase.command.core.SnapshotCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance liquibase.command.core.SyncHubCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance liquibase.sdk.convert.ConvertCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance com.datical.liquibase.ext.command.FormattedDiffCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance com.datical.liquibase.ext.command.RollbackOneChangeSetCommand
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.command.LiquibaseCommand instance com.datical.liquibase.ext.command.RollbackOneUpdateCommand
BEST PRACTICE: The changelog generated by diffChangeLog/generateChangeLog should be inspected for correctness and completeness before being deployed.
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.CatalogSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.ColumnSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.ColumnSnapshotGeneratorH2
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.ColumnSnapshotGeneratorInformix
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.ColumnSnapshotGeneratorOracle
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.ColumnSnapshotGeneratorPostgres
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.DataSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.ForeignKeySnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.IndexSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.PrimaryKeySnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.SchemaSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.SequenceSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.TableSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.UniqueConstraintSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance liquibase.snapshot.jvm.ViewSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.appdba.synonym.SynonymSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.checkconstraint.CheckConstraintSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.checkconstraint.postgres.PostgresCheckConstraintSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.databasepackage.PackageBodySnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.databasepackage.PackageSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.function.FunctionSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.function.postgres.EDBPostgresFunctionSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.function.postgres.PostgresFunctionSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.function.mysql.MySQLFunctionSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.storedproc.PostgresStoredProcedureSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.storedproc.MySQLStoredProcedureSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.storedproc.StoredProcedureSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.trigger.TriggerSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.servicelocator] Loaded liquibase.snapshot.SnapshotGenerator instance com.datical.liquibase.ext.storedlogic.trigger.postgres.PostgresTriggerSnapshotGenerator
[2021-04-01 19:59:57] FINE [liquibase.util] Computed checksum for 1617289197504 as 5f9b3c4715825a4cf29f74ffe357e11a
Unexpected error running Liquibase: java.lang.ClassCastException: class liquibase.ext.mongodb.database.MongoConnection cannot be cast to class liquibase.database.jvm.JdbcConnection (liquibase.ext.mongodb.database.MongoConnection and liquibase.database.jvm.JdbcConnection are in unnamed module of loader 'app')
For more information, please use the --logLevel flag
[2021-04-01 19:59:57] SEVERE [liquibase.integration] Unexpected error running Liquibase: java.lang.ClassCastException: class liquibase.ext.mongodb.database.MongoConnection cannot be cast to class liquibase.database.jvm.JdbcConnection (liquibase.ext.mongodb.database.MongoConnection and liquibase.database.jvm.JdbcConnection are in unnamed module of loader 'app')
liquibase.exception.LiquibaseException: liquibase.command.CommandExecutionException: java.lang.ClassCastException: class liquibase.ext.mongodb.database.MongoConnection cannot be cast to class liquibase.database.jvm.JdbcConnection (liquibase.ext.mongodb.database.MongoConnection and liquibase.database.jvm.JdbcConnection are in unnamed module of loader 'app')
        at liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(CommandLineUtils.java:251)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1542)
        at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:367)
        at liquibase.Scope.lambda$child$0(Scope.java:160)
        at liquibase.Scope.child(Scope.java:169)
        at liquibase.Scope.child(Scope.java:159)
        at liquibase.Scope.child(Scope.java:138)
        at liquibase.integration.commandline.Main$1.run(Main.java:366)
        at liquibase.integration.commandline.Main$1.run(Main.java:196)
        at liquibase.Scope.child(Scope.java:169)
        at liquibase.Scope.child(Scope.java:145)
        at liquibase.integration.commandline.Main.run(Main.java:196)
        at liquibase.integration.commandline.Main.main(Main.java:158)
Caused by: liquibase.command.CommandExecutionException: java.lang.ClassCastException: class liquibase.ext.mongodb.database.MongoConnection cannot be cast to class liquibase.database.jvm.JdbcConnection (liquibase.ext.mongodb.database.MongoConnection and liquibase.database.jvm.JdbcConnection are in unnamed module of loader 'app')
        at liquibase.command.AbstractCommand.execute(AbstractCommand.java:24)
        at liquibase.integration.commandline.CommandLineUtils.doGenerateChangeLog(CommandLineUtils.java:249)
        ... 12 more
Caused by: java.lang.ClassCastException: class liquibase.ext.mongodb.database.MongoConnection cannot be cast to class liquibase.database.jvm.JdbcConnection (liquibase.ext.mongodb.database.MongoConnection and liquibase.database.jvm.JdbcConnection are in unnamed module of loader 'app')
        at liquibase.snapshot.jvm.JdbcSnapshotGenerator.getDatabaseCatalogNames(JdbcSnapshotGenerator.java:144)
        at liquibase.snapshot.jvm.CatalogSnapshotGenerator.snapshotObject(CatalogSnapshotGenerator.java:35)
        at liquibase.snapshot.jvm.JdbcSnapshotGenerator.snapshot(JdbcSnapshotGenerator.java:65)
        at liquibase.snapshot.SnapshotGeneratorChain.snapshot(SnapshotGeneratorChain.java:49)
        at liquibase.snapshot.DatabaseSnapshot.include(DatabaseSnapshot.java:315)
        at liquibase.snapshot.DatabaseSnapshot.init(DatabaseSnapshot.java:100)
        at liquibase.snapshot.DatabaseSnapshot.<init>(DatabaseSnapshot.java:59)
        at liquibase.snapshot.JdbcDatabaseSnapshot.<init>(JdbcDatabaseSnapshot.java:38)
        at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:215)
        at liquibase.snapshot.SnapshotGeneratorFactory.createSnapshot(SnapshotGeneratorFactory.java:188)
        at liquibase.command.core.DiffCommand.createReferenceSnapshot(DiffCommand.java:222)
        at liquibase.command.core.DiffCommand.createDiffResult(DiffCommand.java:144)
        at liquibase.command.core.GenerateChangeLogCommand.run(GenerateChangeLogCommand.java:62)
        at liquibase.command.AbstractCommand.execute(AbstractCommand.java:19)
        ... 13 more
```

`

I've followed the pre-requisites and mentioned version compatibility but still facing this issue.

_Originally posted by asimghub in https://github.com/liquibase/liquibase-mongodb/issues/87#issuecomment-812525675_

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1408) by [Unito](https://www.unito.io/learn-more)

**Comment by alexandru-slobodcicov** [comment]
@asimghub Please provide the command you are trying. Will adjust README with supported mvn plugin or CLI.
The usual ones should be fine: 
update
rollback
tag
dropall

**Comment by asimghub** [comment]
@alexandru-slobodcicov yeah you are right, I was actually using _generateChangeLog_ command. Can you please share the list of allowed commands for community version.

**Comment by homeofthewizard** [comment]
Hello,
Is generateChangeLog will be supported in the future ?

**Comment by GoodnezEverywer** [comment]
is this resolved? generateChangeLog is not working for mongodb. We are trying to import a Json data set to mongod database using liquibase. Since liquibase dosen't accept JSON format to import, we need imported the data in a separate DB and trying generateChangeLog to get the change log, but the command is not working.

**Comment by Nida96** [comment]
Is this issue resolved?

**Comment by kevin-atx** [comment]
@alexandru-slobodcicov - I was reviewing the Liquibase tutorial page and I suspect some of our information is incorrect. I saw your list of supported mongosh commands, but I couldn't find a list of supported Liquibase Commands. Does this extension support any other liquibase commands other than update?
