### ISSUE TITLE
Liquibase commands are failing for other databases when mongodb jars are also present on classpath

### ISSUE THREAD

**Issue by AshwaniPratap8** [liquibase/liquibase-mongodb#146]
Hi,

The liquibase commands for oracle database are failing when mongo-driver and liquibase-mongo extension jars are present on the LIQUIBASE_HOME/lib folder. They run fine if I remove mongo related jars. We managed to run this command when the MongoDB driver is not in the lib folder.

It looks like liquibase is picking the wrong driver. The scenario is like the following:
Place the oracle and the MongoDB driver inside the lib folder and try to execute against Oracle.

Below are various details;

I am using Liquibase 4.3.1 version.

Below jars were present on my LIQUIBASE_HOME/lib folder while running it for Oracle database.
liquibase-mongodb-4.3.1.jar
mongo-java-driver-3.9.1.jar
ojdbc8-12.2.0.1.0.jar

I ran the following command. I ran it without classpath and driver as well and got the same error.
liquibase --driver=oracle.jdbc.driver.OracleDriver --classpath=C:\apps\liquibase-4.3.1\lib\ojdbc8-12.2.0.1.0.jar --url=jdbc:oracle:thin:@blrdev000330.bpc.broadcom.net:1521:EE --username=system --password=oracle --logLevel=debug history

Please find below debug logs.

[2021-04-01 12:33:02] FINE [liquibase.servicelocator] Loaded liquibase.license.LicenseService instance liquibase.pro.license.keymgr.DaticalTrueLicenseService
[2021-04-01 12:33:02] INFO [liquibase.integration] No Liquibase Pro license key supplied. Please set liquibaseProLicenseKey on command line or in liquibase.properties to use Liquibase Pro features.
Liquibase Community 4.3.1 by Datical
####################################################

- - -
| | () () |
| | _ __ _ _ _ | |_ __ _ 

- - -
| | | |/ _ | | | | | '_ \ / _ / __|/ _ \
| || | (| | || | | |) | (| _ \ __/
_/|_, |_,||./ _,|/__|
| |
|_|
Get documentation at docs.liquibase.com
Get certified courses at learn.liquibase.com
Free schema change activity reports at
https://hub.liquibase.com
####################################################
Starting Liquibase at 12:33:02 (version 4.3.1 liquibase/liquibase#26 built at 2021-02-12 17:41+0000)
[2021-04-01 12:33:02] FINE [liquibase.integration] Liquibase Hub URL: https://hub.liquibase.com
[2021-04-01 12:33:02] FINE [liquibase.integration] Liquibase Hub Mode: all
[2021-04-01 12:33:02] FINE [liquibase.resource] Adding path C:\Users\ashwanipratap. to resourceAccessor liquibase.resource.FileSystemResourceAccessor
[2021-04-01 12:33:02] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.CockroachDatabase
[2021-04-01 12:33:02] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.DB2Database
[2021-04-01 12:33:02] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.Db2zDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.DerbyDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.Firebird3Database
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.FirebirdDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.H2Database
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.HsqlDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.InformixDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.Ingres9Database
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.MSSQLDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.MariaDBDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.MockDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.MySQLDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.OracleDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.PostgresDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.SQLiteDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.SybaseASADatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.SybaseDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.UnsupportedDatabase
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.ext.mongodb.database.MongoLiquibaseDatabase
[2021-04-01 12:33:03] FINE [liquibase.database] Properties:
[2021-04-01 12:33:03] FINE [liquibase.database] Key:‘user’ Value:‘system’
[2021-04-01 12:33:03] FINE [liquibase.database] Key:‘password’ Value:’**********’
[2021-04-01 12:33:03] FINE [liquibase.database] Connecting to the URL:‘jdbc:oracle:thin:@blrdev000330.bpc.broadcom.net:1521:EE’ using driver:‘oracle.jdbc.driver.OracleDriver’
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.DatabaseConnection instance liquibase.database.jvm.JdbcConnection
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.DatabaseConnection instance com.datical.liquibase.ext.database.jvm.ProJdbcConnection
[2021-04-01 12:33:03] FINE [liquibase.servicelocator] Loaded liquibase.database.DatabaseConnection instance liquibase.ext.mongodb.database.MongoConnection
Unexpected error running Liquibase: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Could not open connection to database: UNKNOWN
For more information, please use the --logLevel flag
[2021-04-01 12:33:03] SEVERE [liquibase.integration] Unexpected error running Liquibase: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Could not open connection to database: UNKNOWN
liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Could not open connection to database: UNKNOWN
at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:131)
at liquibase.integration.commandline.Main.doMigration(Main.java:1412)
at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:364)
at liquibase.Scope.lambda$child$0(Scope.java:160)
at liquibase.Scope.child(Scope.java:169)
at liquibase.Scope.child(Scope.java:159)
at liquibase.Scope.child(Scope.java:138)
at liquibase.integration.commandline.Main$1.run(Main.java:363)
at liquibase.integration.commandline.Main$1.run(Main.java:193)
at liquibase.Scope.child(Scope.java:169)
at liquibase.Scope.child(Scope.java:145)
at liquibase.integration.commandline.Main.run(Main.java:193)
at liquibase.integration.commandline.Main.main(Main.java:156)
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Could not open connection to database: UNKNOWN
at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:217)
at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:176)
at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:141)
at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:96)
… 12 more
Caused by: liquibase.exception.DatabaseException: liquibase.exception.DatabaseException: Could not open connection to database: UNKNOWN
at liquibase.database.ConnectionServiceFactory.create(ConnectionServiceFactory.java:36)
at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:214)
… 15 more
Caused by: liquibase.exception.DatabaseException: Could not open connection to database: UNKNOWN
at liquibase.ext.mongodb.database.MongoConnection.open(MongoConnection.java:104)
at liquibase.database.ConnectionServiceFactory.create(ConnectionServiceFactory.java:33)
… 16 more
Caused by: java.lang.IllegalArgumentException: The connection string contains invalid user information. If the username or password contains a colon (:slight_smile: or an at-sign (@) then it must be urlencoded
at com.mongodb.ConnectionString.(ConnectionString.java:309)
at liquibase.ext.mongodb.database.MongoConnection.open(MongoConnection.java:96)
… 17 more

Please look into this and suggest the resolution.

Thanks!
Ashwani

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1762) by [Unito](https://www.unito.io)

**Comment by nvoxland** [comment]
I opened a PR for this, although it is also dependent on liquibase/liquibase#1784
