### ISSUE TITLE
Issues with the latest Mongo drivers?

### ISSUE THREAD

**Issue by oliallan14** [liquibase/liquibase-mongodb#149]
Very simple changelog, just creates a collection against an ATLAS cluster

Running: Liquibase:4.3.5, liquibase-mongodb:4.3.5 and mongo driver 3.8.12 

Command line:
liquibase --changeLogFile=db.changelog-master.xml --url="mongodb+srv://<user>:<pwd>@<my_cluster>/<mydb>?retryWrites=true&w=majority" status

Returns:
Liquibase command 'status' was executed successfully

Next, upgrade driver to the latest version here (requires both core and sync driver)
https://mvnrepository.com/artifact/org.mongodb/mongodb-driver-core/4.2.3
https://mvnrepository.com/artifact/org.mongodb/mongodb-driver-sync/4.2.3

Using 4.2.3 driver in place of 3.8.12 in the lib folder of liquibase:

Command line:
liquibase --changeLogFile=db.changelog-master.xml --loglevel=debug --url="mongodb+srv://<user>:<pwd>@<my_cluster>/<mydb>?retryWrites=true&w=majority" status

Returns:

Starting Liquibase at 09:29:38 (version 4.3.5 #62 built at 2021-04-29 18:31+0000)
[2021-06-01 09:29:38] FINE [liquibase.integration] Liquibase Hub URL:      https://hub.liquibase.com
[2021-06-01 09:29:38] FINE [liquibase.integration] Liquibase Hub Mode:     all
[2021-06-01 09:29:38] FINE [liquibase.resource] Adding path /my_working_dir/. to resourceAccessor liquibase.resource.FileSystemResourceAccessor
[2021-06-01 09:29:38] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.CockroachDatabase
[2021-06-01 09:29:38] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.DB2Database
[2021-06-01 09:29:38] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.Db2zDatabase
[2021-06-01 09:29:38] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.DerbyDatabase
[2021-06-01 09:29:38] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.Firebird3Database
[2021-06-01 09:29:38] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.FirebirdDatabase
[2021-06-01 09:29:38] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.H2Database
[2021-06-01 09:29:38] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.HsqlDatabase
[2021-06-01 09:29:38] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.InformixDatabase
[2021-06-01 09:29:38] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.Ingres9Database
[2021-06-01 09:29:38] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.MSSQLDatabase
[2021-06-01 09:29:38] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.MariaDBDatabase
[2021-06-01 09:29:38] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.MockDatabase
[2021-06-01 09:29:38] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.MySQLDatabase
[2021-06-01 09:29:38] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.OracleDatabase
[2021-06-01 09:29:38] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.PostgresDatabase
[2021-06-01 09:29:38] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.SQLiteDatabase
[2021-06-01 09:29:38] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.SybaseASADatabase
[2021-06-01 09:29:38] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.SybaseDatabase
[2021-06-01 09:29:38] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.UnsupportedDatabase
[2021-06-01 09:29:38] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.ext.mongodb.database.MongoLiquibaseDatabase
[2021-06-01 09:29:38] FINE [liquibase.database] Properties:
[2021-06-01 09:29:38] FINE [liquibase.database] Connecting to the URL:'mongodb+srv://<user>:<pwd>@<my_cluster>/<mydb>?retryWrites=true&w=majority' using driver:'liquibase.ext.mongodb.database.MongoClientDriver'
[2021-06-01 09:29:38] FINE [liquibase.servicelocator] Loaded liquibase.database.DatabaseConnection instance liquibase.database.jvm.JdbcConnection
[2021-06-01 09:29:38] FINE [liquibase.servicelocator] Loaded liquibase.database.DatabaseConnection instance com.datical.liquibase.ext.database.jvm.ProJdbcConnection
[2021-06-01 09:29:38] FINE [liquibase.servicelocator] Loaded liquibase.database.DatabaseConnection instance liquibase.ext.mongodb.database.MongoConnection
[2021-06-01 09:29:38] WARNING [com.mongodb.diagnostics.logging.Loggers shouldUseSLF4J] SLF4J not found on the classpath.  Logging is disabled for the 'org.mongodb.driver' component
Unexpected error running Liquibase: org.bson.BsonValue
For more information, please use the --logLevel flag
[2021-06-01 09:29:38] SEVERE [liquibase.integration] Unexpected error running Liquibase: org.bson.BsonValue
java.lang.NoClassDefFoundError: org/bson/BsonValue
	at com.mongodb.ConnectionString.buildWriteConcern(ConnectionString.java:907)
	at com.mongodb.ConnectionString.createWriteConcern(ConnectionString.java:639)
	at com.mongodb.ConnectionString.translateOptions(ConnectionString.java:562)
	at com.mongodb.ConnectionString.<init>(ConnectionString.java:394)
	at liquibase.ext.mongodb.database.MongoConnection.open(MongoConnection.java:96)
	at liquibase.database.ConnectionServiceFactory.create(ConnectionServiceFactory.java:33)
	at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:214)
	at liquibase.database.DatabaseFactory.openConnection(DatabaseFactory.java:176)
	at liquibase.database.DatabaseFactory.openDatabase(DatabaseFactory.java:141)
	at liquibase.integration.commandline.CommandLineUtils.createDatabaseObject(CommandLineUtils.java:96)
	at liquibase.integration.commandline.Main.doMigration(Main.java:1432)
	at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:367)
	at liquibase.Scope.lambda$child$0(Scope.java:160)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:159)
	at liquibase.Scope.child(Scope.java:138)
	at liquibase.integration.commandline.Main$1.run(Main.java:366)
	at liquibase.integration.commandline.Main$1.run(Main.java:196)
	at liquibase.Scope.child(Scope.java:169)
	at liquibase.Scope.child(Scope.java:145)
	at liquibase.integration.commandline.Main.run(Main.java:196)
	at liquibase.integration.commandline.Main.main(Main.java:158)
Caused by: java.lang.ClassNotFoundException: org.bson.BsonValue
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:606)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:168)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:522)
	... 22 more

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1773) by [Unito](https://www.unito.io)

**Comment by oliallan14** [comment]
So the readme lists the following dependencies:

mongodb-driver-sync:4.2.0
snakeyaml:1.27
jackson-annotations:2.11.3
jackson-core:2.11.3
jackson-databind:2.11.3

Actually, the above error is caused by another missing dependency:

bson-4.2.0.jar

Might want to add that to the readme for people manually managing dependencies
