### ISSUE TITLE
Unexpected error running Liquibase: org.bson.Document.getList (NoSuchMethodError)

### ISSUE THREAD

**Issue by devheroo** [liquibase/liquibase-mongodb#150]
Hello,
I am trying to follow the official [tutorial for mongodb](https://docs.liquibase.com/workflows/database-setup-tutorials/mongodb.html), but I am getting this exception:

here is the full log:

> `[2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.license.LicenseService instance liquibase.pro.license.keymgr.DaticalTrueLicenseService
> [2021-06-01 11:34:48] INFO [liquibase.integration] No Liquibase Pro license key supplied. Please set liquibaseProLicenseKey on command line or in liquibase.properties to use Liquibase Pro features.
> Liquibase Community 4.3.5 by Datical
> ####################################################
> ####################################################
> Starting Liquibase at 11:34:48 (version 4.3.5 #62 built at 2021-04-29 18:31+0000)
> [2021-06-01 11:34:48] FINE [liquibase.integration] Liquibase Hub URL:      https://hub.liquibase.com
> [2021-06-01 11:34:48] FINE [liquibase.integration] Liquibase Hub Mode:     all
> [2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.CockroachDatabase
> [2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.DB2Database
> [2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.Db2zDatabase
> [2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.DerbyDatabase
> [2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.Firebird3Database
> [2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.FirebirdDatabase
> [2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.H2Database
> [2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.HsqlDatabase
> [2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.InformixDatabase
> [2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.Ingres9Database
> [2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.MSSQLDatabase
> [2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.MariaDBDatabase
> [2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.MockDatabase
> [2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.MySQLDatabase
> [2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.OracleDatabase
> [2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.PostgresDatabase
> [2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.SQLiteDatabase
> [2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.SybaseASADatabase
> [2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.SybaseDatabase
> [2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.database.core.UnsupportedDatabase
> [2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.database.Database instance liquibase.ext.mongodb.database.MongoLiquibaseDatabase
> [2021-06-01 11:34:48] FINE [liquibase.database] Properties:
> [2021-06-01 11:34:48] FINE [liquibase.database] Connecting to the URL:'mongodb://localhost:27017/myDatabase' using driver:'liquibase.ext.mongodb.database.MongoClientDriver'
> [2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.database.DatabaseConnection instance liquibase.database.jvm.JdbcConnection
> [2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.database.DatabaseConnection instance com.datical.liquibase.ext.database.jvm.ProJdbcConnection
> [2021-06-01 11:34:48] FINE [liquibase.servicelocator] Loaded liquibase.database.DatabaseConnection instance liquibase.ext.mongodb.database.MongoConnection
> [2021-06-01 11:34:49] INFO [com.mongodb.diagnostics.logging.JULLogger log] Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
> [2021-06-01 11:34:49] FINE [liquibase.database] Connection has been created
> [2021-06-01 11:34:49] FINE [liquibase.ext] Connected to @localhost:27017
> [2021-06-01 11:34:49] FINE [liquibase.ext] Not adjusting the auto commit mode; it is already false
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.Catalog
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.Column
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.Data
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.ForeignKey
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.Index
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.PrimaryKey
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.Schema
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.Sequence
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.StoredProcedure
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.Table
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.UniqueConstraint
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance liquibase.structure.core.View
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance com.datical.liquibase.ext.appdba.synonym.Synonym
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance com.datical.liquibase.ext.storedlogic.checkconstraint.CheckConstraint
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance com.datical.liquibase.ext.storedlogic.databasepackage.DatabasePackage
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance com.datical.liquibase.ext.storedlogic.databasepackage.DatabasePackageBody
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance com.datical.liquibase.ext.storedlogic.function.Function
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.structure.DatabaseObject instance com.datical.liquibase.ext.storedlogic.trigger.Trigger
> [2021-06-01 11:34:49] INFO [com.mongodb.diagnostics.logging.JULLogger log] Opened connection [connectionId{localValue:1, serverValue:15}] to localhost:27017
> [2021-06-01 11:34:49] INFO [com.mongodb.diagnostics.logging.JULLogger log] Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 0, 6]}, minWireVersion=0, maxWireVersion=7, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=5076800}
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.lockservice.LockService instance liquibase.lockservice.LockServiceImpl
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.lockservice.LockService instance liquibase.lockservice.MockLockService
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.lockservice.LockService instance liquibase.lockservice.OfflineLockService
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.lockservice.LockService instance liquibase.lockservice.StandardLockService
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.lockservice.LockService instance liquibase.ext.mongodb.lockservice.MongoLockService
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.executor.Executor instance liquibase.executor.jvm.JdbcExecutor
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.executor.Executor instance com.datical.liquibase.ext.OracleSqlPlusExecutor
> [2021-06-01 11:34:49] FINE [liquibase.servicelocator] Loaded liquibase.executor.Executor instance liquibase.nosql.executor.NoSqlExecutor
> [2021-06-01 11:34:49] INFO [com.mongodb.diagnostics.logging.JULLogger log] Opened connection [connectionId{localValue:2, serverValue:16}] to localhost:27017
> [2021-06-01 11:34:49] INFO [com.mongodb.diagnostics.logging.JULLogger log] Closed connection [connectionId{localValue:2, serverValue:16}] to localhost:27017 because the pool has been closed.
> Unexpected error running Liquibase: org.bson.Document.getList(Ljava/lang/Object;Ljava/lang/Class;)Ljava/util/List;
> For more information, please use the --logLevel flag
> [2021-06-01 11:34:49] SEVERE [liquibase.integration] Unexpected error running Liquibase: org.bson.Document.getList(Ljava/lang/Object;Ljava/lang/Class;)Ljava/util/List;
> java.lang.NoSuchMethodError: org.bson.Document.getList(Ljava/lang/Object;Ljava/lang/Class;)Ljava/util/List;
> 	at liquibase.ext.mongodb.statement.AbstractRunCommandStatement.checkResponse(AbstractRunCommandStatement.java:78)
> 	at liquibase.ext.mongodb.statement.AbstractRunCommandStatement.run(AbstractRunCommandStatement.java:60)
> 	at liquibase.ext.mongodb.statement.AbstractRunCommandStatement.run(AbstractRunCommandStatement.java:55)
> 	at liquibase.ext.mongodb.statement.ListCollectionNamesStatement.queryForList(ListCollectionNamesStatement.java:79)
> 	at liquibase.ext.mongodb.statement.CountCollectionByNameStatement.queryForLong(CountCollectionByNameStatement.java:44)
> 	at liquibase.ext.mongodb.statement.CountCollectionByNameStatement.queryForLong(CountCollectionByNameStatement.java:33)
> 	at liquibase.nosql.executor.NoSqlExecutor.queryForLong(NoSqlExecutor.java:105)
> 	at liquibase.nosql.executor.NoSqlExecutor.queryForLong(NoSqlExecutor.java:98)
> 	at liquibase.ext.mongodb.lockservice.MongoLockService.existsRepository(MongoLockService.java:85)
> 	at liquibase.nosql.lockservice.AbstractNoSqlLockService.hasDatabaseChangeLogLockTable(AbstractNoSqlLockService.java:305)
> 	at liquibase.nosql.lockservice.AbstractNoSqlLockService.init(AbstractNoSqlLockService.java:93)
> 	at liquibase.nosql.lockservice.AbstractNoSqlLockService.acquireLock(AbstractNoSqlLockService.java:155)
> 	at liquibase.nosql.lockservice.AbstractNoSqlLockService.waitForLock(AbstractNoSqlLockService.java:119)
> 	at liquibase.Liquibase.lambda$update$1(Liquibase.java:220)
> 	at liquibase.Scope.lambda$child$0(Scope.java:160)
> 	at liquibase.Scope.child(Scope.java:169)
> 	at liquibase.Scope.child(Scope.java:159)
> 	at liquibase.Scope.child(Scope.java:138)
> 	at liquibase.Liquibase.runInScope(Liquibase.java:2369)
> 	at liquibase.Liquibase.update(Liquibase.java:217)
> 	at liquibase.Liquibase.update(Liquibase.java:203)
> 	at liquibase.integration.commandline.Main.doMigration(Main.java:1802)
> 	at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:367)
> 	at liquibase.Scope.lambda$child$0(Scope.java:160)
> 	at liquibase.Scope.child(Scope.java:169)
> 	at liquibase.Scope.child(Scope.java:159)
> 	at liquibase.Scope.child(Scope.java:138)
> 	at liquibase.integration.commandline.Main$1.run(Main.java:366)
> 	at liquibase.integration.commandline.Main$1.run(Main.java:196)
> 	at liquibase.Scope.child(Scope.java:169)
> 	at liquibase.Scope.child(Scope.java:145)
> 	at liquibase.integration.commandline.Main.run(Main.java:196)
> 	at liquibase.integration.commandline.Main.main(Main.java:158)
> 
> `

┆Issue is synchronized with this [Jira Bug](https://datical.atlassian.net/browse/LB-1774) by [Unito](https://www.unito.io)

**Comment by devheroo** [comment]
I figured out the problem, I was not using the latest java mongodb driver as I thought, the release page is not sorting the versions correctly https://repo1.maven.org/maven2/org/mongodb/mongo-java-driver/, the latest version is not at the bottom of the list but somewhere in the middle. so I suggested to document this note.
