### ISSUE TITLE
Liquibase fails with json changelogs running against MongoDB

### ISSUE THREAD

**Issue by kataggart** [liquibase/liquibase-mongodb#234]
After attempting to run json changelogs from the following [link](https://github.com/liquibase/liquibase-mongodb/tree/main/src/test/resources/liquibase/ext/json) we are getting an error message to initiate Liquibase.

Steps to reproduce

1 - Connect to MongoDB 2 - Run the following [changelog](https://github.com/liquibase/liquibase-mongodb/tree/main/src/test/resources/liquibase/ext/json#:~:text=changelog.generic.json) with the update command

Actual results

```
Starting Liquibase at 18:52:52 (version 4.6.1 #98 built at 2021-11-04 20:16+0000)
Liquibase Version: 4.6.1
Liquibase Community 4.6.1 by Liquibase
[2021-12-22 18:52:52] INFO [com.mongodb.diagnostics.logging.JULLogger log] Cluster created with settings {hosts=[localhost:27017], mode=SINGLE, requiredClusterType=UNKNOWN, serverSelectionTimeout='30000 ms', maxWaitQueueSize=500}
[2021-12-22 18:52:52] INFO [com.mongodb.diagnostics.logging.JULLogger log] Opened connection [connectionId{localValue:1, serverValue:9}] to localhost:27017
[2021-12-22 18:52:52] INFO [com.mongodb.diagnostics.logging.JULLogger log] Monitor thread successfully connected to server with description ServerDescription{address=localhost:27017, type=STANDALONE, state=CONNECTED, ok=true, version=ServerVersion{versionList=[4, 4, 5]}, minWireVersion=0, maxWireVersion=9, maxDocumentSize=16777216, logicalSessionTimeoutMinutes=30, roundTripTimeNanos=4873490}
[2021-12-22 18:52:52] INFO [com.mongodb.diagnostics.logging.JULLogger log] Opened connection [connectionId{localValue:2, serverValue:10}] to localhost:27017
[2021-12-22 18:52:52] INFO [com.mongodb.diagnostics.logging.JULLogger log] Closed connection [connectionId{localValue:2, serverValue:10}] to localhost:27017 because the pool has been closed.
[2021-12-22 18:52:52] SEVERE [liquibase.integration] java.lang.NullPointerException
liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: Unknown reason
        at liquibase.command.CommandScope.execute(CommandScope.java:156)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:45)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:15)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:325)
        at liquibase.Scope.child(Scope.java:186)
        at liquibase.Scope.child(Scope.java:162)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:291)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:80)
Caused by: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: Unknown reason
        at liquibase.integration.commandline.Main$1.run(Main.java:442)
        at liquibase.integration.commandline.Main$1.run(Main.java:220)
        at liquibase.Scope.child(Scope.java:186)
        at liquibase.Scope.child(Scope.java:162)
        at liquibase.integration.commandline.Main.run(Main.java:220)
        at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:32)
        at liquibase.command.CommandScope.execute(CommandScope.java:150)
        ... 14 more
Caused by: liquibase.exception.LockException: java.lang.NullPointerException
        at liquibase.nosql.lockservice.AbstractNoSqlLockService.acquireLock(AbstractNoSqlLockService.java:182)
        at liquibase.nosql.lockservice.AbstractNoSqlLockService.waitForLock(AbstractNoSqlLockService.java:118)
        at liquibase.Liquibase.lambda$update$1(Liquibase.java:214)
        at liquibase.Scope.lambda$child$0(Scope.java:177)
        at liquibase.Scope.child(Scope.java:186)
        at liquibase.Scope.child(Scope.java:176)
        at liquibase.Scope.child(Scope.java:155)
        at liquibase.Liquibase.runInScope(Liquibase.java:2404)
        at liquibase.Liquibase.update(Liquibase.java:211)
        at liquibase.Liquibase.update(Liquibase.java:197)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1875)
        at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:397)
        at liquibase.Scope.lambda$child$0(Scope.java:177)
        at liquibase.Scope.child(Scope.java:186)
        at liquibase.Scope.child(Scope.java:176)
        at liquibase.Scope.child(Scope.java:155)
        at liquibase.integration.commandline.Main$1.run(Main.java:396)
        ... 20 more
Caused by: java.lang.NullPointerException
        at liquibase.ext.mongodb.lockservice.MongoLockService.adjustRepository(MongoLockService.java:97)
        at liquibase.nosql.lockservice.AbstractNoSqlLockService.init(AbstractNoSqlLockService.java:101)
        at liquibase.nosql.lockservice.AbstractNoSqlLockService.acquireLock(AbstractNoSqlLockService.java:154)
        ... 36 more


Unexpected error running Liquibase: java.lang.NullPointerException

liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: Unknown reason
        at liquibase.command.CommandScope.execute(CommandScope.java:156)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:45)
        at liquibase.integration.commandline.CommandRunner.call(CommandRunner.java:15)
        at picocli.CommandLine.executeUserObject(CommandLine.java:1953)
        at picocli.CommandLine.access$1300(CommandLine.java:145)
        at picocli.CommandLine$RunLast.executeUserObjectOfLastSubcommandWithSameParent(CommandLine.java:2352)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2346)
        at picocli.CommandLine$RunLast.handle(CommandLine.java:2311)
        at picocli.CommandLine$AbstractParseResultHandler.execute(CommandLine.java:2179)
        at picocli.CommandLine.execute(CommandLine.java:2078)
        at liquibase.integration.commandline.LiquibaseCommandLine.lambda$execute$1(LiquibaseCommandLine.java:325)
        at liquibase.Scope.child(Scope.java:186)
        at liquibase.Scope.child(Scope.java:162)
        at liquibase.integration.commandline.LiquibaseCommandLine.execute(LiquibaseCommandLine.java:291)
        at liquibase.integration.commandline.LiquibaseCommandLine.main(LiquibaseCommandLine.java:80)
Caused by: liquibase.exception.LiquibaseException: Unexpected error running Liquibase: Unknown reason
        at liquibase.integration.commandline.Main$1.run(Main.java:442)
        at liquibase.integration.commandline.Main$1.run(Main.java:220)
        at liquibase.Scope.child(Scope.java:186)
        at liquibase.Scope.child(Scope.java:162)
        at liquibase.integration.commandline.Main.run(Main.java:220)
        at liquibase.command.AbstractCliWrapperCommandStep.run(AbstractCliWrapperCommandStep.java:32)
        at liquibase.command.CommandScope.execute(CommandScope.java:150)
        ... 14 more
Caused by: liquibase.exception.LockException: java.lang.NullPointerException
        at liquibase.nosql.lockservice.AbstractNoSqlLockService.acquireLock(AbstractNoSqlLockService.java:182)
        at liquibase.nosql.lockservice.AbstractNoSqlLockService.waitForLock(AbstractNoSqlLockService.java:118)
        at liquibase.Liquibase.lambda$update$1(Liquibase.java:214)
        at liquibase.Scope.lambda$child$0(Scope.java:177)
        at liquibase.Scope.child(Scope.java:186)
        at liquibase.Scope.child(Scope.java:176)
        at liquibase.Scope.child(Scope.java:155)
        at liquibase.Liquibase.runInScope(Liquibase.java:2404)
        at liquibase.Liquibase.update(Liquibase.java:211)
        at liquibase.Liquibase.update(Liquibase.java:197)
        at liquibase.integration.commandline.Main.doMigration(Main.java:1875)
        at liquibase.integration.commandline.Main$1.lambda$run$0(Main.java:397)
        at liquibase.Scope.lambda$child$0(Scope.java:177)
        at liquibase.Scope.child(Scope.java:186)
        at liquibase.Scope.child(Scope.java:176)
        at liquibase.Scope.child(Scope.java:155)
        at liquibase.integration.commandline.Main$1.run(Main.java:396)
        ... 20 more
Caused by: java.lang.NullPointerException
        at liquibase.ext.mongodb.lockservice.MongoLockService.adjustRepository(MongoLockService.java:97)
        at liquibase.nosql.lockservice.AbstractNoSqlLockService.init(AbstractNoSqlLockService.java:101)
        at liquibase.nosql.lockservice.AbstractNoSqlLockService.acquireLock(AbstractNoSqlLockService.java:154)
        ... 36 more
```

Expected results

Update should be sucessfull for with the expected created collection from the changelog

**Comment by kataggart** [comment]
[source ticket](https://datical.atlassian.net/browse/DAT-8909)

**Comment by nvoxland** [comment]
I've not been able to reproduce this. Waiting for more repo information
