### ISSUE TITLE
renameCollection feature

### ISSUE THREAD

**Issue by isalciuc** [liquibase/liquibase-mongodb#369]
I didn't find any way to rename a collection in MongoDB using Liquibase

**Comment by Ygilany** [comment]
@isalciuc renaming a collection is an adminCommand.

Here's an example for how you can do that
```json
{
  "databaseChangeLog": [
    {
      "changeSet": {
        "id": "2023.05.22.1",
        "author": "Yahya Gilany",
        "comment": "Rename collections",
        "changes": [
          {
            "adminCommand": {
              "command": {
                "$rawJson": {
                  "renameCollection": "database-name.old-collection-name",
                  "to": "database-name.new-collection-name"
                }
              }
            }
          }
        ]
      }
    }
  ]
}
```

**Comment by isalciuc** [comment]
It fails with a not very informative NPE exception:


> Caused by: java.lang.NullPointerException: null
> 	at liquibase.ext.mongodb.statement.AdminCommandStatement.run(AdminCommandStatement.java:51)
> 	at liquibase.ext.mongodb.statement.AbstractRunCommandStatement.execute(AbstractRunCommandStatement.java:51)
> 	at liquibase.ext.mongodb.statement.AbstractRunCommandStatement.execute(AbstractRunCommandStatement.java:36)
> 	at liquibase.nosql.executor.NoSqlExecutor.execute(NoSqlExecutor.java:187)


It also requires to run it as admin and to know the database name.

On the other hand, this command doesn't require to run as admin and to know the databse name:

> db.<source-collection-name>.renameCollection("<new-collection-name>")

**Comment by GevorgPetrosyan** [comment]
To rename a MongoDB collection using Liquibase, you can implement a custom Java class that utilizes the MongoDB Java driver to perform the renaming operation. This approach involves creating a class that implements the liquibase.change.custom.CustomTaskChange interface, allowing you to define custom behavior within your Liquibase changelog.

Create the Custom Java Class:

Develop a Java class that implements the CustomTaskChange interface. This class will contain the logic to rename the MongoDB collection.
```

import com.mongodb.client.MongoDatabase;
import com.mongodb.client.MongoNamespace;
import com.mongodb.client.model.RenameCollectionOptions;
import liquibase.change.custom.CustomTaskChange;
import liquibase.database.Database;
import liquibase.exception.CustomChangeException;
import liquibase.exception.SetupException;
import liquibase.exception.ValidationErrors;
import liquibase.resource.ResourceAccessor;
import liquibase.ext.mongodb.database.LiquibaseMongoConnection;

public class RenameCollectionChange implements CustomTaskChange {
    private String oldCollectionName;
    private String newCollectionName;

    public void setOldCollectionName(String oldCollectionName) {
        this.oldCollectionName = oldCollectionName;
    }

    public void setNewCollectionName(String newCollectionName) {
        this.newCollectionName = newCollectionName;
    }

    @Override
    public void execute(Database database) throws CustomChangeException {
        try {
            MongoDatabase mongoDatabase = ((LiquibaseMongoConnection) database.getConnection()).getMongoDatabase();
            mongoDatabase.getCollection(oldCollectionName)
                .renameCollection(new MongoNamespace(mongoDatabase.getName(), newCollectionName), new RenameCollectionOptions().dropTarget(false));
        } catch (Exception e) {
            throw new CustomChangeException("Error renaming collection from '" + oldCollectionName + "' to '" + newCollectionName + "'", e);
        }
    }

    @Override
    public String getConfirmationMessage() {
        return "Collection '" + oldCollectionName + "' successfully renamed to '" + newCollectionName + "'";
    }

    @Override
    public void setUp() throws SetupException {
        // No setup required
    }

    @Override
    public void setFileOpener(ResourceAccessor resourceAccessor) {
        // Not needed for this implementation
    }

    @Override
    public ValidationErrors validate(Database database) {
        ValidationErrors validationErrors = new ValidationErrors();
        if (oldCollectionName == null || oldCollectionName.isEmpty()) {
            validationErrors.addError("oldCollectionName is required");
        }
        if (newCollectionName == null || newCollectionName.isEmpty()) {
            validationErrors.addError("newCollectionName is required");
        }
        return validationErrors;
    }
}
```

In your Liquibase changelog file (e.g., JSOn format), reference the custom change class and provide the necessary parameters.
```
{
  "databaseChangeLog": [
    {
      "changeSet": {
        "id": "rename-collection-1",
        "author": "your-username",
        "changes": [
          {
            "customChange": {
              "class": "your.package.RenameCollectionChange",
              "oldCollectionName": "oldCollectionName",
              "newCollectionName": "newCollectionName"
            }
          }
        ]
      }
    }
  ]
}
```
