### ISSUE TITLE
Unsupported authMechanism: MONGODB-AWS

### ISSUE THREAD

**Issue by benoit-campeau** [liquibase/liquibase-mongodb#481]
Hello,

When i try running liquibase update, i get this error

`Caused by: liquibase.exception.DatabaseException: Could not open connection to database: mongodb+srv://workflow-tracker-dev.pzz49.mongodb.net/workflowdb?authMechanism=MONGODB-AWS
        at liquibase.ext.mongodb.database.MongoConnection.open(MongoConnection.java:121)
        at liquibase.database.ConnectionServiceFactory.create(ConnectionServiceFactory.java:32)
        ... 25 more
Caused by: java.lang.IllegalArgumentException: Unsupported authMechanism: MONGODB-AWS
        at com.mongodb.AuthenticationMechanism.fromMechanismName(AuthenticationMechanism.java:99)
        at com.mongodb.ConnectionString.createCredentials(ConnectionString.java:703)
        at com.mongodb.ConnectionString.<init>(ConnectionString.java:396)
        at liquibase.ext.mongodb.database.MongoConnection.open(MongoConnection.java:109)
        ... 26 more
`
Not Sure why i get this.  Double checked any typo.  This exact same uri work fine when running the app.

**Comment by vitaliimak** [comment]
Hi @benoit-campeau, thank you for reporting this issue.
The extension does not support MONGODB-AWS authMechanism right now. Would you be willing to submit a PR for this?
